# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-22 16:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='darft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2018, 1, 22, 16, 32, 52, 893765, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
