# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-24 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20180122_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='darft',
            new_name='draft',
        ),
    ]
